# Generated by Django 3.0.8 on 2020-07-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
