# Generated by Django 3.0.8 on 2020-07-27 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestImports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilePath', models.CharField(max_length=255)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Deleted', models.BooleanField()),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManifestRecordCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedAliquots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleType', models.CharField(max_length=100)),
                ('Volume', models.CharField(max_length=500)),
                ('VolumeUnit', models.CharField(max_length=2)),
                ('PostProcessingStatus', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RecieptRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.CharField(max_length=10)),
                ('Clinic', models.CharField(max_length=50)),
                ('DateTimeTaken', models.DateTimeField()),
                ('SampleId', models.CharField(max_length=8)),
                ('TissueSubType', models.CharField(max_length=4)),
                ('ReceivedDateTime', models.DateTimeField()),
                ('Volume', models.CharField(max_length=500)),
                ('VolumeUnit', models.CharField(max_length=4)),
                ('Condition', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.CharField(max_length=10)),
                ('TissueSubType', models.CharField(max_length=4)),
                ('ReceivedDateTime', models.DateTimeField()),
                ('ProcessedDateTime', models.DateTimeField()),
                ('Volume', models.CharField(max_length=500)),
                ('VolumeUnit', models.CharField(max_length=2)),
                ('NumberOfChildren', models.CharField(max_length=500)),
                ('SiteHeld', models.CharField(max_length=100)),
                ('ParentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecieptRecordsSampleId', to='blood_sample.RecieptRecords')),
            ],
        ),
        migrations.CreateModel(
            name='ManifestRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visit', models.CharField(max_length=10)),
                ('Site', models.CharField(max_length=100)),
                ('Room', models.CharField(max_length=20)),
                ('CohortId', models.CharField(max_length=7)),
                ('Barcode', models.CharField(max_length=10)),
                ('CollectionDateTime', models.DateTimeField()),
                ('ImportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManifestRecordsImportId', to='blood_sample.ManifestImports')),
            ],
        ),
        migrations.CreateModel(
            name='BloodSampleImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilePath', models.CharField(max_length=255)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Deleted', models.BooleanField()),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BloodSampleCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodSample',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('CohortId', models.CharField(max_length=7)),
                ('Barcode', models.CharField(max_length=10)),
                ('AppointmentId', models.BigIntegerField()),
                ('SiteNurseEmail', models.CharField(max_length=255)),
                ('Comments', models.CharField(max_length=5000)),
                ('CreatedAt', models.DateTimeField()),
                ('ImportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BloodSampleImportImportId', to='blood_sample.BloodSampleImport')),
            ],
        ),
    ]
