# Generated by Django 3.0.8 on 2020-08-17 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood_sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestrecords',
            name='Comments',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='processedreport',
            name='Comments',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='receiptrecords',
            name='Comments',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='manifestrecords',
            name='Site',
            field=models.CharField(choices=[(0, 'FMH'), (1, 'KGH'), (2, 'Mile End Hospital'), (3, 'UCLH')], max_length=1),
        ),
        migrations.AlterField(
            model_name='manifestrecords',
            name='Visit',
            field=models.CharField(choices=[(0, 'Y0'), (1, 'Y0+3M'), (2, 'Y1'), (3, 'Y2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='processedaliquots',
            name='SampleType',
            field=models.CharField(choices=[(0, 'RBC'), (1, 'Plasma'), (2, 'BuffyCoat'), (3, 'Plasma')], max_length=1),
        ),
        migrations.CreateModel(
            name='ReceiptChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field', models.CharField(max_length=50)),
                ('FromValue', models.CharField(max_length=5000)),
                ('ChangedAt', models.DateTimeField(auto_now=True)),
                ('ChangedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReceiptChangedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedReportChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field', models.CharField(max_length=50)),
                ('FromValue', models.CharField(max_length=5000)),
                ('ChangedAt', models.DateTimeField(auto_now=True)),
                ('ChangedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProcessedReportChangedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedAliquotsChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field', models.CharField(max_length=50)),
                ('FromValue', models.CharField(max_length=5000)),
                ('ChangedAt', models.DateTimeField(auto_now=True)),
                ('ChangedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProcessedAliquotsChangedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field', models.CharField(max_length=50)),
                ('FromValue', models.CharField(max_length=5000)),
                ('ChangedAt', models.DateTimeField(auto_now=True)),
                ('ChangedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManifestChangedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
